schema: workflow/2022.04
name: NOLA Events
settings:
  error_notification: true
triggers:
- id: hi_PrHpRDw
steps:
- namespace: getEvents
  runtime: python3.12
  uses: "./getEvents/entry.py"
  props:
    __configurableProps:
    - name: data_store
      type: data_store
    data_store:
      storeId: ds_A2unn7q
- namespace: returnResult
  runtime: python3.12
  uses: "./returnResult/entry.py"

