schema: workflow/2022.04
name: Identify and Alert on Cats
settings:
  error_notification: true
triggers:
- id: hi_Y4HmWPp
steps:
- namespace: get_image
  runtime: python3.12
  uses: "./get_image/entry.py"
- namespace: upload_to_gemini
  runtime: python3.12
  uses: "./upload_to_gemini/entry.py"
- namespace: item_detection
  runtime: python3.12
  uses: "./item_detection/entry.py"
- namespace: check_for_targets
  runtime: python3.12
  uses: "./check_for_targets/entry.py"
- namespace: exit_if_no_match
  runtime: python3.12
  uses: "./exit_if_no_match/entry.py"
- namespace: create_email_text
  runtime: python3.12
  uses: "./create_email_text/entry.py"
- namespace: send_email_to_self
  runtime: nodejs20.x
  uses: email-send-email-to-self@0.4.4
  props:
    subject: Match found in Image
    text: "{{steps.create_email_text.$return_value.email}}"
    html: "{{steps.create_email_text.$return_value.email}}"

